app = "top100tokens"
primary_region = "fra"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  
  [[http_service.checks]]
    interval = 10000
    grace_period = "5s"
    method = "GET"
    path = "/health"
    timeout = 2000

[vm]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1