app = "top100tokens"
primary_region = "fra"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  
  [[http_service.checks]]
    interval = "10s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    timeout = "2s"

[[vm]]
  memory = "1024"
  cpu_kind = "shared"
  cpus = 1